### ISSUE TITLE
32 64

### ISSUE THREAD

**Issue by SportPlusX** [JasonkayZK/bark-cli#2]
bark-cli.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

**Comment by JasonkayZK** [comment]
请问您的windows是64位的吗？我发布的windows版本是在Linux下交叉编译的二进制，可能存在部分兼容性问题！

**Comment by SportPlusX** [comment]
64bit

**Comment by JasonkayZK** [comment]
> 
> 
> 64bit
我这边重新编译发布了win下的，您在试一下哦~

**Comment by SportPlusX** [comment]
已解决
